export const data = {
  game_type: 'person',
  player_total_points: 20,
  computer_total_points: 27,
  player_total_answers: 29,
  answers: [
    {
      id: 56,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth Maul',
      computer_answer: 'Darth Maul',
      img: '../static/assets/img/modes/people/12.jpg',
      is_correct: true,
      points: 1,
    },
    {
      id: 22,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth foo',
      computer_answer: 'Darth Maul',
      img: '../static/assets/img/modes/people/4.jpg',
      is_correct: false,
      points: 0,
    },
    {
      id: 17,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth elooo',
      computer_answer: 'Darth Maul',
      img: '../static/assets/img/modes/people/4.jpg',
      is_correct: false,
      points: 0,
    },
    {
      id: 56,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth Maul',
      computer_answer: 'Dath Maul',
      img: '../static/assets/img/modes/people/1.jpg',
      is_correct: true,
      points: 1,
    },
    {
      id: 22,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth foo',
      computer_answer: 'Darth Maul',
      img: '../static/assets/img/modes/people/1.jpg',
      is_correct: false,
      points: 0,
    },
    {
      id: 17,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth elooo',
      computer_answer: 'Darth Maul',
      img: '../static/assets/img/modes/people/12.jpg',
      is_correct: false,
      points: 0,
    },
    {
      id: 56,
      correct_answer: 'Darth Maul',
      player_answer: 'Darth Maul',
      computer_answer: 'Darth guuu',
      img: '../static/assets/img/modes/people/1.jpg',
      is_correct: true,
      points: 1,
    },
    {
      id: 16,
      correct_answer: 'Lorem ipsum',
      player_answer: 'Ipsum lore',
      computer_answer: 'tttt Maul',
      img: '../static/assets/img/modes/people/12.jpg',
      is_correct: false,
      points: 0,
    },
  ],
};
